spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    initialization-mode: always
    username: dev_db_user
    password: dev_database_password
    driver-class-name: org.postgresql.Driver

base.url: http://localhost:8080
